// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwF9HBuk5idm7qiQFTBDwuOqhmywzbd0U',
    appId: '1:798872087535:web:7f4a0f6353e882dcd6641a',
    messagingSenderId: '798872087535',
    projectId: 'accountingapp-79edf',
    authDomain: 'accountingapp-79edf.firebaseapp.com',
    storageBucket: 'accountingapp-79edf.firebasestorage.app',
    measurementId: 'G-G5XCLRPVP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrj89Rh4kMtehlXQ7j2658KRbR2M1C22Q',
    appId: '1:798872087535:android:fa1b3a0914be055fd6641a',
    messagingSenderId: '798872087535',
    projectId: 'accountingapp-79edf',
    storageBucket: 'accountingapp-79edf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_sPcfznjyY74xLGIVgDCY9fJ5QpbfHG8',
    appId: '1:798872087535:ios:dda782c8d7599a8ed6641a',
    messagingSenderId: '798872087535',
    projectId: 'accountingapp-79edf',
    storageBucket: 'accountingapp-79edf.firebasestorage.app',
    iosBundleId: 'com.example.accounting360',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_sPcfznjyY74xLGIVgDCY9fJ5QpbfHG8',
    appId: '1:798872087535:ios:dda782c8d7599a8ed6641a',
    messagingSenderId: '798872087535',
    projectId: 'accountingapp-79edf',
    storageBucket: 'accountingapp-79edf.firebasestorage.app',
    iosBundleId: 'com.example.accounting360',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwF9HBuk5idm7qiQFTBDwuOqhmywzbd0U',
    appId: '1:798872087535:web:ba615105ea2f5b42d6641a',
    messagingSenderId: '798872087535',
    projectId: 'accountingapp-79edf',
    authDomain: 'accountingapp-79edf.firebaseapp.com',
    storageBucket: 'accountingapp-79edf.firebasestorage.app',
    measurementId: 'G-D5LR3RRXJ1',
  );
}
